config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :education_histories
  resources :work_histories
  resources :resumes
  devise_for :users
  root 'welcome#index'

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :users do
      	resources :resumes, only: [:index, :create, :show, :update, :destroy]
        resources :resumes do
	 resources :work_histories, only: [:index, :create, :show, :update, :destroy]
	 resources :education_histories, only: [:index, :create, :show, :update, :destroy]
	end
      end
    end
  end

end

app/models/education_history.rb
class EducationHistory < ActiveRecord::Base
  delegate :user, :to=> :user, :allow_nil=>false
  belongs_to :resume
  validates :school_name, :from, :until, :education, presence: true
  resourcify
end

app/controllers/api/v1/education_histories_controller.rb
class Api::V1::EducationHistoriesController < Api::V1::BaseController
  before_action :set_education_history, only: [:show,:update, :destroy]
  load_and_authorize_resource :user
  load_and_authorize_resource :resume, :through => :user,:shallow=>true
  load_and_authorize_resource :education_history, :through => :resume,:shallow=>true

  include ActiveHashRelation

  def_param_group :education_history do
    param :education, String, :desc => "Education (type of education) ", :required => false
    param :from, String, :desc => "From (date description, 04/12/2001 for instance) ", :required => false
    param :until, String, :desc => "Until (date description, 04/12/2001 for instance), should be greater than from date ", :required => false
    param :school_name, String, :desc => "Name of the school ", :required => false
  end

  api :GET, "/v1/users/:user_id/resumes/:resume_id/education_histories/:id", "Get education_history data"
  formats ['json']
  def show
    if can? :read, EducationHistory
      render(json: Api::V1::EducationHistorySerializer.new(@education_history).to_json)
    end
  end

  api :POST, "/v1/users/:user_id/resumes/:resume_id/education_histories", "add new education_history data to resume"
  param_group :education_history
  formats ['json']
  def create
    if can? :create, EducationHistory
      @education_history = EducationHistory.new(education_history_params)
      if current_user.has_role?(:admin)
        # admin can add to any resume
        @resume = Resume.find(params[:resume_id])
      else
        # user can only add to own resumes
        @resume = Resume.where(["id=? and user_id = ?",params[:resume_id],current_user.id]).first
      end
      if !@resume.nil? and @education_history.save!
        render(json: Api::V1::EducationHistorySerializer.new(@education_history).to_json)
      else
        render :json => { :errors => @education_history.errors.full_messages }
      end
    end
  end

  api :PUT, "/v1/users/:user_id/resumes/:resume_id/education_histories/:id", "Update education_history data"
  param_group :education_history
  formats ['json']
  def update
    if can? :update, EducationHistory
      if current_user.has_role?(:admin) or (current_user.has_role?(:user) and @education_history.resume.user.id == current_user.id)
        if @education_history.update(education_history_params)
          render(json: Api::V1::EducationHistorySerializer.new(@education_history).to_json)
        else
          render :json => { :errors => @education_history.errors.full_messages }
        end
      else
        render :json => { :error => "This is not allowed" }
      end
    end
  end

  api :DELETE, "/v1/users/:user_id/resumes/:resume_id/education_histories/:id", "Delete education_history data"
  formats ['json']
  def destroy
    if can? :destroy, EducationHistory
      if @education_history.destroy
        render :json => { :succes => "education_history destroyed" }
      else
        render :json => { :errors => @education_history.errors.full_messages }
      end
    else
      render :json => { :error => "This is not allowed" }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_education_history
    @education_history = EducationHistory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def education_history_params
    params.require(:education_history).permit(:resume_id,:from,:until,:school_name,:education)
  end


end

app/controllers/education_histories_controller.rb
class EducationHistoriesController < ApplicationController
  before_action :set_education_history, only: [:show, :edit, :update, :destroy]

  # GET /education_histories
  # GET /education_histories.json
  def index
    @education_histories = EducationHistory.all
  end

  # GET /education_histories/1
  # GET /education_histories/1.json
  def show
  end

  # GET /education_histories/new
  def new
    @education_history = EducationHistory.new
  end

  # GET /education_histories/1/edit
  def edit
  end

  # POST /education_histories
  # POST /education_histories.json
  def create
    @education_history = EducationHistory.new(education_history_params)

    respond_to do |format|
      if @education_history.save
        format.html { redirect_to @education_history, notice: 'Education history was successfully created.' }
        format.js   { render }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /education_histories/1
  # PATCH/PUT /education_histories/1.json
  def update
    respond_to do |format|
      if @education_history.update(education_history_params)
        format.html { redirect_to @education_history, notice: 'Education history was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /education_histories/1
  # DELETE /education_histories/1.json
  def destroy
    @education_history.destroy
    respond_to do |format|
      format.html { redirect_to education_histories_url, notice: 'Education history was successfully destroyed.' }
      format.js   { render }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_history
      @education_history = EducationHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_history_params
      params.require(:education_history).permit(:resume_id,:school_name,:from,:until)
    end
end

app/helpers/education_histories_helper.rb
module EducationHistoriesHelper
end

app/views/education_histories/_form.html.erb
<% if @education_history.nil?
	@education_history = EducationHistory.new
	@education_history[:resume_id] = resume_id
	@education_history[:from] = (Time.now - 1.year).strftime("%m/%d/%Y")
	@education_history[:until] = (Time.now).strftime("%m/%d/%Y")

end
%>
<%= simple_form_for(@education_history,:remote=>true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :resume_id, :as=>:hidden %>
    <%= f.input :school_name %>
    <%= f.input :education %>
    <%= f.input :from, :as=>:hidden %>
    <%= f.input :until, :as=>:hidden %>
    <div class="form-group string optional education_history_from_until">
	     <label class="string optional control-label" for="education_history_from_until">
	        Time period
	     </label>
	     <input class="string optional form-control" type="text" name="from_until" id="education_history_from_until"/>
    </div>
  </div>

<script type="text/javascript">
$( document ).ready(function() {
	$('#education_history_from_until').daterangepicker({
	    "showDropdowns": true,
	    "showWeekNumbers": true,
	    "timePickerIncrement": 1,
	    "startDate": $("#education_history_from").val(),
	    "endDate": $("#education_history_until").val(),
	    "opens": "left",
	    "drops": "down",
	    "buttonClasses": "btn btn-sm",
	    "applyClass": "btn-success",
	    "cancelClass": "btn-warning"
	  }, function(start, end, label) {
	  	$("#education_history_from").val(start.format('MM/DD/YYYY'))
	  	$("#education_history_until").val(end.format("MM/DD/YYYY"))
	 });
});
</script>


  <div class="form-actions">
    <%= f.button :submit, :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/education_histories/_index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>School name</th>
            <th>Education</th>
            <th>From</th>
            <th>Until</th>
            <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, education_histories) do |education_history| %>
            <td><%= education_history.school_name %></td>
            <td><%= education_history.education %></td>
            <td><%= education_history.from %></td>
            <td><%= education_history.until %></td>
        <td><%= link_to fa_icon(:trash), education_history, method: :delete, :remote => true, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/education_histories/create.js.erb
<%
	partial = render :partial => 'education_histories/index', :locals => {:education_histories => @education_history.resume.education_histories.order("'from' desc") }
%>
$("#educationhistoryform").collapse();
$("#education_histories").html("<%= escape_javascript(partial) %>");

app/views/education_histories/destroy.js.erb
$("#education_history_<%= @education_history.id.to_s %>").remove();

app/views/education_histories/edit.html.erb
<div class="page-header">
  <%= link_to education_histories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @education_history, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing education_history</h1>
</div>

<%= render 'form' %>

app/views/education_histories/index.html.erb
<div class="page-header">
  <%= link_to new_education_history_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Education history
  <% end %>
  <h1>Listing education_histories</h1>
</div>

<%= render :partial => "index",:locals=>{:education_histories=>@education_histories} %>

app/views/education_histories/new.html.erb
<div class="page-header">
  <%= link_to education_histories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New education_history</h1>
</div>

<%= render 'form' %>

app/views/education_histories/show.html.erb
<div class="page-header">
  <%= link_to education_histories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_education_history_path(@education_history), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show education_history</h1>
</div>

<dl class="dl-horizontal">
  <dt>Resume:</dt>
  <dd><%= @education_history.resume_id %></dd>

</dl>