config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :education_histories
  resources :work_histories
  resources :resumes
  devise_for :users
  root 'welcome#index'

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :users do
      	resources :resumes, only: [:index, :create, :show, :update, :destroy]
        resources :resumes do
	 resources :work_histories, only: [:index, :create, :show, :update, :destroy]
	 resources :education_histories, only: [:index, :create, :show, :update, :destroy]
	end
      end
    end
  end

end

app/models/work_history.rb
class WorkHistory < ActiveRecord::Base
    delegate :user, :to=> :user, :allow_nil=>false
    belongs_to :resume
    validates :company_name, :from, :until, :position, presence: true
    resourcify
end

app/controllers/api/v1/work_histories_controller.rb
class Api::V1::WorkHistoriesController < Api::V1::BaseController
  before_action :set_work_history, only: [:show,:update, :destroy]
  load_and_authorize_resource :user
  load_and_authorize_resource :resume, :through => :user,:shallow=>true
  load_and_authorize_resource :work_history, :through => :resume,:shallow=>true

  include ActiveHashRelation

  def_param_group :work_history do
    param :education, String, :desc => "Education (type of education) ", :required => false
    param :from, String, :desc => "From (date description, 04/12/2001 for instance) ", :required => false
    param :until, String, :desc => "Until (date description, 04/12/2001 for instance), should be greater than from date ", :required => false
    param :school_name, String, :desc => "Name of the school/university ", :required => false
  end

  api :GET, "/v1/users/:user_id/resumes/:resume_id/work_histories/:id", "Get work_history data (array)"
  formats ['json']
  def show
    if can? :read, WorkHistory
      render(json: Api::V1::WorkHistorySerializer.new(@work_history).to_json)
    end
  end

  api :POST, "/v1/users/:user_id/resumes/:resume_id/work_histories", "Get education_history data"
  param_group :work_history
  formats ['json']
  def create
    if can? :create, WorkHistory
      @work_history = WorkHistory.new(work_history_params)
      if current_user.has_role?(:admin)
        # admin can add to any resume
        @resume = Resume.find(params[:resume_id])
      else
        # user can only add to own resumes
        @resume = Resume.where(["id=? and user_id = ?",params[:resume_id],current_user.id]).first
      end
      if !@resume.nil? and @work_history.save!
        render(json: Api::V1::WorkHistorySerializer.new(@work_history).to_json)
      else
        render :json => { :errors => @work_history.errors.full_messages }
      end
    end
  end

  api :PUT, "/v1/users/:user_id/resumes/:resume_id/work_histories/:id", "Update education_history data"
  param_group :work_history
  formats ['json']
  def update
    if can? :update, WorkHistory
      if current_user.has_role?(:admin) or (current_user.has_role?(:user) and @work_history.resume.user.id == current_user.id)
        if @work_history.update(work_history_params)
          render(json: Api::V1::WorkHistorySerializer.new(@work_history).to_json)
        else
          render :json => { :errors => @work_history.errors.full_messages }
        end
      else
        render :json => { :error => "This is not allowed" }
      end
    end
  end

  api :DELETE, "/v1/users/:user_id/resumes/:resume_id/work_histories/:id", "Get work_history data (array)"
  formats ['json']
  def destroy
    if can? :destroy, WorkHistory
      if @work_history.destroy
        render :json => { :succes => "work_history destroyed" }
      else
        render :json => { :errors => @work_history.errors.full_messages }
      end
    else
      render :json => { :error => "This is not allowed" }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_work_history
    @work_history = WorkHistory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def work_history_params
    params.require(:work_history).permit(:resume_id,:position,:from,:until,:company_name)
  end


end

app/controllers/work_histories_controller.rb
class WorkHistoriesController < ApplicationController
  before_action :set_work_history, only: [:show, :edit, :update, :destroy]

  # GET /work_histories
  # GET /work_histories.json
  def index
    @work_histories = WorkHistory.all
  end

  # GET /work_histories/1
  # GET /work_histories/1.json
  def show
  end

  # GET /work_histories/new
  def new
    @work_history = WorkHistory.new
  end

  # GET /work_histories/1/edit
  def edit
  end

  # POST /work_histories
  # POST /work_histories.json
  def create
    @work_history = WorkHistory.new(work_history_params)

    respond_to do |format|
      if @work_history.save
        format.html { redirect_to @work_history, notice: 'Work history was successfully created.' }
        format.js   { render }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /work_histories/1
  # PATCH/PUT /work_histories/1.json
  def update
    respond_to do |format|
      if @work_history.update(work_history_params)
        format.html { redirect_to @work_history, notice: 'Work history was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /work_histories/1
  # DELETE /work_histories/1.json
  def destroy
    @work_history.destroy
    respond_to do |format|
      format.html { redirect_to work_histories_url, notice: 'Work history was successfully destroyed.' }
      format.js   { render }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_history
      @work_history = WorkHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_history_params
      params.require(:work_history).permit(:resume_id,:position,:from,:until,:company_name)
    end
end

app/helpers/work_histories_helper.rb
module WorkHistoriesHelper
end

app/views/work_histories/_form.html.erb
<% if @work_history.nil?
	@work_history = WorkHistory.new
	@work_history[:resume_id] = resume_id
	@work_history[:from] = (Time.now - 1.year).strftime("%m/%d/%Y")
	@work_history[:until] = (Time.now).strftime("%m/%d/%Y")

end
%>
<%= simple_form_for(@work_history,:remote=>true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :resume_id, :as=>:hidden %>
    <%= f.input :company_name %>
    <%= f.input :position %>
    <%= f.input :from, :as=>:hidden %>
    <%= f.input :until, :as=>:hidden %>
    <div class="form-group string optional work_history_from_until">
	     <label class="string optional control-label" for="work_history_from_until">
	        Time period
	     </label>
	     <input class="string optional form-control" type="text" name="from_until" id="work_history_from_until"/>
    </div>
  </div>

<script type="text/javascript">
$( document ).ready(function() {
	$('#work_history_from_until').daterangepicker({
	    "showDropdowns": true,
	    "showWeekNumbers": true,
	    "timePickerIncrement": 1,
	    "startDate": $("#work_history_from").val(),
	    "endDate": $("#work_history_until").val(),
	    "opens": "left",
	    "drops": "down",
	    "buttonClasses": "btn btn-sm",
	    "applyClass": "btn-success",
	    "cancelClass": "btn-warning"
	  }, function(start, end, label) {
	  	$("#work_history_from").val(start.format('MM/DD/YYYY'))
	  	$("#work_history_until").val(end.format("MM/DD/YYYY"))
	 });
});
</script>

  <div class="form-actions">
    <%= f.button :submit, :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/work_histories/_index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Company name</th>
            <th>Position</th>
            <th>From</th>
            <th>Until</th>
            <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, work_histories) do |work_history| %>
            <td><%= work_history.company_name %></td>
            <td><%= work_history.position %></td>
            <td><%= work_history.from %></td>
            <td><%= work_history.until %></td>
        <td><%= link_to fa_icon(:trash), work_history, method: :delete, :remote => true, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/work_histories/create.js.erb
<%
	partial = render :partial => 'work_histories/index', :locals => {:work_histories => @work_history.resume.work_histories.order("'from' desc") }
%>
$("#workhistoryform").collapse();
$("#work_histories").html("<%= escape_javascript(partial) %>");

app/views/work_histories/destroy.js.erb
$("#work_history_<%= @work_history.id.to_s %>").remove();

app/views/work_histories/edit.html.erb
<div class="page-header">
  <%= link_to work_histories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @work_history, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing work_history</h1>
</div>

<%= render 'form' %>

app/views/work_histories/index.html.erb
<div class="page-header">
  <%= link_to new_work_history_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Work history
  <% end %>
  <h1>Listing work_histories</h1>
</div>

<%= render :partial => "index",:locals=>{:work_histories=>@work_histories} %>

app/views/work_histories/new.html.erb
<div class="page-header">
  <%= link_to work_histories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New work_history</h1>
</div>

<%= render 'form' %>

app/views/work_histories/show.html.erb
<div class="page-header">
  <%= link_to work_histories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_work_history_path(@work_history), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show work_history</h1>
</div>

<dl class="dl-horizontal">
  <dt>Resume:</dt>
  <dd><%= @work_history.resume_id %></dd>

</dl>