config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :education_histories
  resources :work_histories
  resources :resumes
  devise_for :users
  root 'welcome#index'

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :users do
      	resources :resumes, only: [:index, :create, :show, :update, :destroy]
        resources :resumes do
	 resources :work_histories, only: [:index, :create, :show, :update, :destroy]
	 resources :education_histories, only: [:index, :create, :show, :update, :destroy]
	end
      end
    end
  end

end

app/models/resume.rb
class Resume < ActiveRecord::Base
    belongs_to :user
    has_many :work_histories
    has_many :education_histories
    validates :name, presence: true
    resourcify
end

app/controllers/api/v1/resumes_controller.rb
class Api::V1::ResumesController < Api::V1::BaseController
  before_action :set_resume, only: [:show,:update, :destroy]
  load_and_authorize_resource

  include ActiveHashRelation

  api :GET, "/v1/users/:user_id/resumes/:id", "Get resume"
  description <<-EOS
  == Get all users
  Get an array of all users and their data.
  EOS
  formats ['json']
  def show
    if can? :read, Resume
      render(json: Api::V1::ResumeSerializer.new(@resume).to_json)
    end
  end

  api :POST, "/v1/users/:user_id/resumes", "Create resume"
  param :name, String, :desc => "Name", :required => false
  formats ['json']
  def create
    if can? :create, Resume
      @resume = Resume.new(resume_params)
      if !current_user.has_role?(:admin)
        @resume[:user_id] = current_user.id
      end
      if @resume.save
        render(json: Api::V1::ResumeSerializer.new(@resume).to_json)
      else
        render :json => { :errors => @resume.errors.full_messages }
      end
    end
  end

  api :PUT, "/v1/users/:user_id/resumes/:id", "Update resume"
  param :name, String, :desc => "Name", :required => false
  formats ['json']
  def update
    if can? :update, Resume
      if @resume.update(resume_params)
        render(json: Api::V1::ResumeSerializer.new(@resume).to_json)
      else
        render :json => { :errors => @resume.errors.full_messages }
      end
    end
  end

  api :DELETE, "/v1/users/:user_id/resumes/:id", "Create resume"
  formats ['json']
  def destroy
    if can? :destroy, Resume
      if @resume.destroy
        render :json => { :succes => "resume destroyed" }
      else
        render :json => { :errors => @resume.errors.full_messages }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_resume
    @resume = Resume.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def resume_params
    params.require(:resume).permit(:name,:user_id)
  end


end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)
    if current_user.has_role?(:user)
      # only admin can set another user
      logger.info("BLAAA")
      @resume[:user_id] = current_user[:id]
    end
    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:user_id,:name)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= simple_form_for(@resume) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% if current_user.has_role?(:admin) %>
        <%= f.input :user_id,:label=>"User that this resume belongs to",:as=>:select, :collection=>User.all.order("email asc"),:label_method => :email,:value_method => :id,:include_blank => false %>
    <% end %>
    <%= f.input :name,:label=>"Name of this resume" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<div class="page-header">
  <%= link_to resumes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @resume, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing resume</h1>
</div>

<%= render 'form' %>

app/views/resumes/index.html.erb
<div class="page-header">
  <%= link_to new_resume_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Resume
  <% end %>
  <h1>Listing resumes</h1>
</div>

<% if @resumes.nil? or @resumes.length == 0 %>
<div class="alert alert-warning" role="alert">No resumes present yet</div>

<% else %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
              <th>User</th>
              <th>Resume Name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @resumes) do |resume| %>
          <td><%= resume.inspect %></td>
          <td><%= link_to 'Show', resume %></td>
          <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
          <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/resumes/new.html.erb
<div class="page-header">
  <%= link_to resumes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New resume</h1>
</div>

<%= render 'form' %>

app/views/resumes/show.html.erb
<div class="page-header">
  <%= link_to resumes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_resume_path(@resume), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1 class="lobster"><%= @resume.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @resume.user.email %></dd>

</dl>

<h2 class="lobster">Work history</h2>
<% if @resume.work_histories.blank? %>
No work experience yet
<% else %>
<div id="work_histories">
  <%= render :partial => "work_histories/index",:locals=>{:work_histories=>@resume.work_histories.order("'from' desc")} %>
</div>
<% end %>
<div id="workhistoryform" class="collapse">
  <%= render :partial => "work_histories/form",:locals=>{:resume_id=>@resume.id} %>
</div>
<BR>
<a class="btn btn-primary" id="addworkhistory_btn" data-toggle="collapse" data-target="#workhistoryform">Add work history</a>

<h2 class="lobster">Education history</h2>
<% if @resume.education_histories.blank? %>
No education history yet
<% else %>
<div id="education_histories">
  <%= render :partial => "education_histories/index",:locals=>{:education_histories=>@resume.education_histories.order("'from' desc")} %>
</div>
<% end %>
<div id="educationhistoryform" class="collapse">
  <%= render :partial => "education_histories/form",:locals=>{:resume_id=>@resume.id} %>
</div>
<BR>
<a class="btn btn-primary" id="addeducationhistory_btn" data-toggle="collapse" data-target="#educationhistoryform">Add education history</a>